/**
 * 149 creative variants of the orqlaude tagline.
 *
 * Used by the bare-`orql` easter egg (src/cli/easter_egg.ts): a random
 * tagline is typed out, paused, erased, and the cycle repeats. The
 * picker guarantees consecutive picks are never the same string.
 *
 * Index 0 is the "canonical" descriptive tagline used elsewhere as a
 * watermark fallback. The rest are intentionally varied — technical,
 * playful, poetic, self-aware — to keep the easter egg interesting.
 */

export const TAGLINES: readonly string[] = [
  "multi-agent orchestrator for Claude Code",
  "a fleet of Agnets, one tame Claude",
  "parallel Claudes, sane budget",
  "herding cats — but the cats are Claudes",
  "like git, but for Claude sessions",
  "one approval, N pull requests",
  "tmux for the AI age",
  "the conductor your fleet was missing",
  "teaching Claude to delegate",
  "one Claude, many Agnets",
  "because one Claude is never enough",
  "fan-out, fan-in, ship",
  "parallel thought, serial commits",
  "branching by intent, not just by git",
  "concurrency for cognition",
  "orchestration, with budget caps",
  "plans, prompts, Agnets, PRs",
  "for when one window isn't enough",
  "spawn → broker → collect",
  "let Claude split itself",
  "cap your fleet, watch them ship",
  "coral-colored coordination",
  "the foreman your repo needed",
  "distributed thinking, atomic commits",
  "a brokerage for Agnets",
  "budget-aware parallelism",
  "an MCP that orchestrates other MCPs",
  "tasks in, branches out",
  "Agnets shipping in formation",
  "one master Claude, many apprentices",
  "the swarm protocol",
  "structured chaos",
  "when one Claude meets many problems",
  "parallel coding, serial review",
  "let Claude phone a friend (and a friend, and a friend)",
  "multi-process minds",
  "fan-out PRs for grown-ups",
  "token budgets and worktree isolation",
  "each Agnet in its own room",
  "orchestration without the spreadsheet",
  "ten Agnets, one approval",
  'the answer to "this would be faster with five Claudes"',
  "herd your AI like livestock",
  "for tasks too big for one mind",
  "supervised parallelism",
  "Claude × N, with rails",
  "one Claude conducts, the rest perform",
  "parallel reads, parallel writes, single source of truth",
  "multi-track recording for code",
  "the band conductor for your AI orchestra",
  "divide, conquer, merge",
  "distributed cognition, concentrated effort",
  "Agnets work in parallel; you stay in control",
  "less waiting, more shipping",
  "let Claude scale horizontally",
  "think wider, ship faster",
  "parallel Claudes without the chaos",
  "the missing primitive for AI fleets",
  "token-budget orchestration",
  "spawn N Claudes, get N PRs",
  "broker, observer, conductor",
  "the choir director for code-writing",
  "simultaneous reasoning, sequential merges",
  "multi-Agnet fleets that don't collide",
  "one fleet, no friction",
  'when "let me also do X" needs a budget',
  "mass-produced thinking, hand-finished code",
  "concurrent Claudes, atomic merges",
  "one orchestrator, many soloists",
  "coordinated Agnets, isolated worktrees",
  "a fleet manager for the AI age",
  "teach Claude to fan-out",
  "multi-window thinking, single-window approval",
  "one Claude can't, so we spawn more",
  "fleet command for code",
  "shipping at the speed of N",
  "the air-traffic control for your Agnets",
  "one approval gate, many ships",
  "orchestrated minds, isolated workspaces",
  "budget the fleet, watch them fly",
  "distributed Claudes, focused work",
  "one human, one approval, N Claudes",
  "Agnet management, not micromanagement",
  "Claude clone army (but tame)",
  "parallel intent, serialized merges",
  "the conductor for your Claude symphony",
  "one mind sets direction, many minds execute",
  "concurrent Claudes, harmonious git",
  "fleet-as-a-pattern",
  "multi-Claude scaffolding",
  "parallel coding with safety rails",
  "one ledger, many Agnets",
  "ship more, supervise less",
  "distributed reasoning, focused output",
  "let Claude scale you, not stress you",
  "fan-out, fan-in, applaud",
  "multi-tab thinking for code",
  "parallel Claudes that actually finish",
  "concurrent thinking, ordered shipping",
  "fleet captain for your AI",
  "one approval gate, ten ships",
  "parallel Claudes, single source of truth",
  "multi-Claude with worktree isolation",
  "fan-out is easy; fan-in is what we do",
  "budgeted parallelism, predictable cost",
  "coordinated Agnets, isolated repos",
  "Claude scaling for grown-ups",
  "structured parallelism for AI",
  "distributed thinking, concentrated approval",
  "multi-window minds, single-window decision",
  "concurrent coding, atomic commits",
  "orchestrated minds, isolated bodies",
  "parallel reasoning with budgets",
  "fleet protocol for Claude",
  "one approval, many merges",
  "parallel Agnets that share what matters",
  "structured ways to spawn Claudes",
  "concurrent Claudes with manners",
  "the missing layer for AI fleets",
  "parallel intent, structured shipping",
  "coordinated minds, isolated worktrees",
  "fleet-mode for Claude",
  "one Claude reads, many Claudes write",
  "multi-Claude scaffolding with budgets",
  "structured fan-out for AI",
  "orchestrated Claudes, predictable output",
  "parallel coding with broker rails",
  "fleet management for the new age",
  "multi-Claude coordination",
  "one approval, N parallel shipments",
  "distributed Claudes, central authority",
  "parallel Agnets, central ledger",
  "structured AI parallelism",
  "fleet-shape for Claude work",
  "parallel coding with one foreman",
  "one ledger, many parallel ships",
  "orchestrated reasoning at scale",
  "concurrent Claudes with safety nets",
  "parallel intent, ordered execution",
  "fleet-aware Claude orchestration",
  "coordinated AI workers, isolated workspaces",
  "structured ways to spawn N Claudes",
  "parallel Agnets with shared awareness",
  "fleet command, AI-flavored",
  "orchestrated minds with budget caps",
  "parallel Claudes, single approval",
  "ship N PRs in the time it takes for one",
  "the multi-Claude pattern, productized",
  "designed for the kind of task that wants a swarm",
];
